---
#Firstly we need to enable VLANs on the MX
    - name: Enable Vlans on the MX
      cisco.meraki.networks_appliance_vlans_settings:
        state: present
        networkId: "{{ create_network.meraki_response.id }}"
        vlansEnabled: true

#Now we begin the process of createing each VLAN, some are sourced from prompts others are a hard coded Subnet
    - name: Create Management Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        id: '1'
        applianceIp: "{{ mgmt_subnet }}.1"
        cidr: "{{ mgmt_subnet }}.0/24"
        name: Management
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: "{{ mgmt_subnet }}.0/24"

    - name: Create User Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        id: '10'
        applianceIp: "{{ user_subnet }}.1"
        cidr: "{{ user_subnet }}.0/24"
        name: Users
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: "{{ user_subnet }}.0/24"

    - name: Create Printer Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        id: '20'
        applianceIp: "{{ print_subnet }}.1"
        cidr: "{{ print_subnet }}.0/24"
        name: Printers
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: "{{ print_subnet }}.0/24"

    - name: Create Wireless Corporate Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: "{{ CorpWiFi_subnet }}.1"
        cidr: "{{ CorpWiFi_subnet }}.0/24"
        id: '100'
        name: Corp WiFi
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: "{{ CorpWiFi_subnet }}.0/24"

    - name: Create Wireless Mobile Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: 10.10.220.1
        cidr: 10.10.220.0/24
        id: '200'
        name: Mobile WiFi
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: 10.10.220.0/24

    - name: Create Wireless Guest Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: 10.10.230.1
        cidr: 10.10.230.0/24
        id: '300'
        name: Guest WiFi
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: 10.10.230.0/24